### ISSUE TITLE
e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid device ordinal

### ISSUE THREAD

**Issue by haijiecheng** [mahyarnajibi/SNIPER#107]
@mahyarnajibi ,hello, please tell me how to deal with this question? thank you!
aaa
Traceback (most recent call last):
  File "main_train.py", line 145, in <module>
    epoch_end_callback=epoch_end_callback, arg_params=arg_params, aux_params=aux_params)
  File "SNIPER-mxnet/python/mxnet/module/base_module.py", line 484, in fit
    for_training=True, force_rebind=force_rebind)
  File "SNIPER-mxnet/python/mxnet/module/module.py", line 430, in bind
    state_names=self._state_names)
  File "SNIPER-mxnet/python/mxnet/module/executor_group.py", line 265, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "SNIPER-mxnet/python/mxnet/module/executor_group.py", line 361, in bind_exec
    shared_group))
  File "SNIPER-mxnet/python/mxnet/module/executor_group.py", line 639, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "SNIPER-mxnet/python/mxnet/symbol/symbol.py", line 1524, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
bbox_target: (16, 84L, 32L, 32L)
im_info: (16, 3L)
valid_ranges: (16, 2L)
label: (16, 21504L)
gt_boxes: (16, 100L, 5L)
bbox_weight: (16, 84L, 32L, 32L)
data: (16, 3L, 512L, 512L)
[18:06:05] src/storage/storage.cc:65: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid device ordinal

**Comment by huynhtnhut97** [comment]
The same to me when im trying to train on VOC dataset.

**Comment by huynhtnhut97** [comment]
I have solved this error. Just change the GPU ID in gpus option in config file according to your system gpus.
If u manage to run on GPU 0 then change it to 0.
