### ISSUE TITLE
cuda error when run the demo

### ISSUE THREAD

**Issue by sherylwang** [mahyarnajibi/SNIPER#15]
hi, I've tried to run the 'demo.py' file, then met the error like: 
mxnet.base.MXNetError: [22:56:26] /home/vis/xuxiaqing/code/code_my/video_detection/SNIPER/SNIPER-mxnet/src/operator/nn/batch_norm.cu:527: Check failed: err == cudaSuccess (7 vs. 0) Name: BatchNormalizationUpdateOutput ErrStr:too many resources requested for launch

My cuda version is 8.0, the cudnn version is 5.0.  Are there any tips for solving this problem? many thanks~

**Comment by sherylwang** [comment]
The problem still occurs after changing the cudnn to version 6.0

**Comment by jwnsu** [comment]
GPU spec? The error commonly comes from insufficient GPU memory.

**Comment by sherylwang** [comment]
My workstation has 4 K40 gpu cards, each has 12G memory. @jwnsu

**Comment by jwnsu** [comment]
Then the issue is not video memory.

**Comment by Jerry3062** [comment]
@sherylwang 
Hi
    I met the same problem, DId you solve it?

**Comment by mahyarnajibi** [comment]
Hi @sherylwang @Jerry3062 ,
Can you pull the SNIPER ```master```, SNIPER-mxnet ```master``` and recompile MXNet using the ```make``` command (README is updated) to see if the problem still exists when running ```demo.py```?

**Comment by sherylwang** [comment]
@mahyarnajibi  The problem has been solved after I pulled the code, really appreciate for the fast update.
